CREATE TABLE IF NOT EXISTS silver_trips (
    vendor_id INTEGER,
    tpep_pickup_datetime TIMESTAMP,
    tpep_dropoff_datetime TIMESTAMP,
    passenger_count DOUBLE,
    trip_distance DOUBLE,
    ratecode_id DOUBLE,
    store_and_fwd_flag VARCHAR,
    pickup_location_id INTEGER,
    dropoff_location_id INTEGER,
    payment_type BIGINT,
    fare_amount DOUBLE,
    extra DOUBLE,
    mta_tax DOUBLE,
    tip_amount DOUBLE,
    tolls_amount DOUBLE,
    improvement_surcharge DOUBLE,
    total_amount DOUBLE,
    congestion_surcharge DOUBLE,
    airport_fee DOUBLE,
    cbd_congestion_fee DOUBLE,
    trip_minutes DOUBLE,
    pickup_month DATE
);

CREATE TABLE IF NOT EXISTS fact_trips (
    trip_id VARCHAR,
    vendor_id INTEGER,
    tpep_pickup_datetime TIMESTAMP,
    tpep_dropoff_datetime TIMESTAMP,
    passenger_count DOUBLE,
    trip_distance DOUBLE,
    ratecode_id DOUBLE,
    store_and_fwd_flag VARCHAR,
    pickup_location_id INTEGER,
    dropoff_location_id INTEGER,
    fare_amount DOUBLE,
    extra DOUBLE,
    mta_tax DOUBLE,
    tip_amount DOUBLE,
    tolls_amount DOUBLE,
    improvement_surcharge DOUBLE,
    total_amount DOUBLE,
    congestion_surcharge DOUBLE,
    airport_fee DOUBLE,
    cbd_congestion_fee DOUBLE,
    trip_minutes DOUBLE,
    pickup_month DATE,
    payment_id BIGINT
);
